std = "max"
files['.luacheckrc'].global = false
unused_args = false

globals = {
        "bit",
        "buffer",
        "collectionfactory",
        "collectionproxy",
        "crash",
        "factory",
        "go",
        "gui",
        "html5",
        "http",
        "image",
        "json",
        "label",
        "model",
        "msg",
        "particlefx",
        "physics",
        "profiler",
        "render",
        "resource",
        "socket",
        "sound",
        "spine",
        "sprite",
        "sys",
        "tilemap",
        "timer",
        "vmath",
        "window",
        "zlib",
        "editor",

        "hash",
        "hash_to_hex",
        "pprint",

        "init",
        "final",
        "on_message",
        "on_input",
        "on_reload",
        "update",

        "defos",
        "fmod",

        "describe",
        "context",
        "spec",
        "it",
        "test",
        "expect",
        "should",
        "they",
        "before",
        "setup",
        "after",
        "teardown",
        "assert_blank",
        "assert_empty",
        "assert_equal",
        "assert_error",
        "assert_false",
        "assert_greater_than",
        "assert_gte",
        "assert_less_than",
        "assert_lte",
        "assert_match",
        "assert_nil",
        "assert_true",
        "assert_type",
        "assert_not_blank",
        "assert_not_empty",
        "assert_not_equal",
        "assert_not_error",
        "assert_not_false",
        "assert_not_greater_than",
        "assert_not_gte",
        "assert_not_less_than",
        "assert_not_lte",
        "assert_not_match",
        "assert_not_nil",
        "assert_not_true",
        "assert_not_type",
        "assert_same",
        "assert_unique",
}