local pick = require "crit.pick"

local h_tint = hash("tint")

local idle_color = vmath.vector4(1.0)
local hover_color = vmath.vector4(1.0, 0.0, 0.0, 1.0)

function init(self)
	self.sprite = msg.url("dot#sprite")
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == nil then
		local is_hovered = pick.pick_sprite(self.sprite, action.x, action.y)
		sprite.set_constant(self.sprite, h_tint, is_hovered and hover_color or idle_color)
	end
end