name: Generate documentation
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Lua
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: luajit

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Install lua-discount
      run: >
        curl http://www.pell.portland.or.us/\~orc/Code/discount/discount-2.2.6.tar.bz2 > discount.tar.bz2 &&
        tar xf discount.tar.bz2 &&
        cd discount-2.2.6 &&
        ./configure.sh &&
        make CFLAGS="-fPIC" &&
        sudo make install &&
        luarocks install https://gitlab.com/craigbarnes/lua-discount/-/raw/master/discount-scm-1.rockspec

    - name: Install LDoc
      run: luarocks install ldoc

    - name: Generate docs
      run: ldoc .

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc